---
resources:
- name: test-repo
  type: git
  source:
    uri: https://github.com/manuelstofer/test-repo.git

jobs:
- name: build-test-repo
  public: true
  serial: true
  plan:
  - aggregate:
    - get: test-repo
      trigger: true
  - task: build-context
    config:
      platform: "linux"
      image_resource:
        type: "docker-image"
        source:
          repository: "debian"
      input:
      - name: test-repo
      run:
        path: bash
        args:
        - test-repo/tests.sh
