---
resources:
- name: test-repo
  type: git
  source:
    uri: git@github.com:smallpdf/test-repo.git

jobs:
- name: build-pro-ci
  public: true
  serial: true
  plan:
  - aggregate:
    - get: test-repo
  - task: build-context
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: debian }
      - name: test-repo
      run:
        path: bash
        args:
        - test-repo/tests.sh
